[package]
name = "viewer"
version = "0.1.1"
readme = "README.md"
description = "Camera image viewer"
edition = "2021"
license-file = "LICENSE"

[[bin]]
name = "viewer"
path = "src/main.rs"

[dependencies]
camera = { path = "../camera" }
numeris = { path = "../numeris" }
svbony = { path = "../svbony" }
thiserror = "2"
num-traits = "0.2.18"
chrono = "0.4.42"
png = "0.18.0"
slint = "1.13.1"
fast_image_resize = "5.3.0"
rgb = "0.8.5"

[dev-dependencies]
approx = "0.5.0" # used for testing

[build-dependencies]
slint-build = "1.13.1"

[features]
svbony = []


[profile.test]
opt-level = 3
