
import {Shared} from "shared.slint";


component VertBar inherits Rectangle {
    x: 0;
    y: 0;
    width: 0.5rem;
    height: 100%;
    in-out property <color> gcolor: yellow;
    background: @linear-gradient(90deg, #333 0%, gcolor 30%, #333 90%);
}

component XAxis inherits Rectangle {
    in-out property <length> labelfontsize: 12px;
    in-out property <length> tickfontsize: 10px;
    in-out property <string> label: "xlabel";
    in-out property <{min: float, max: float}> range: { min: 0, max: 1 };
    in-out property <int> numticks: 5;
    height: 40px + th.height;

    th := Text {
        text: label;
        font-size: labelfontsize;
        y: parent.height - th.height - 8px;
    }

    for i in self.numticks: Path {
        width: 2px;
        height: 12px;
        x: i * parent.width / (parent.numticks - 1) - self.width / 2;
        y: - 4px;
        stroke-width: 1px;
        stroke: #333;
        MoveTo {
            x: 0;
            y: 0;
        }

        LineTo {
            x: 0;
            y: 100;
        }
    }
    for i in self.numticks: Rectangle {
        x: i * parent.width / (parent.numticks - 1) - thx.width / 2;
        y: thx.height;
        thx := Text {
            text: range.min + (i * (range.max - range.min) / (numticks - 1));
            font-size: tickfontsize;
            x: 0;
            y: 0;
            color: #333;
            horizontal-alignment: center;
        }
    }
}

component YAxis inherits Rectangle {
    in-out property <length> labelfontsize: 12px;
    in-out property <length> tickfontsize: 10px;
    in-out property <string> label: "ylabel";
    in-out property <{min: float, max: float}> range: { min: 0, max: 1 };
    in-out property <int> numticks: 5;
    width: 60px + tw.height;
    property <length> maxtickwidth: 0;

    tw := Text {
        text: label;
        font-size: labelfontsize;
        x: 4px + tw.height / 2;
        y: (parent.height) / 2;
        rotation-angle: -90deg;
        rotation-origin-x: 0;
        rotation-origin-y: tw.height / 2;
    }

    for i in self.numticks: Path {
        width: 12px;
        height: 2px;
        x: parent.width - 4px;
        y: i * parent.height / (parent.numticks - 1);
        stroke-width: 1px;
        stroke: #333;
        MoveTo {
            x: 0;
            y: 0;
        }

        LineTo {
            x: 100;
            y: 0;
        }
    }

    for i in self.numticks: Rectangle {
        x: parent.width - thy.width - 4px;
        y: i * parent.height / (parent.numticks - 1) - thy.height / 2;
        thy := Text {
            text: range.max - (i * (range.max - range.min) / (numticks - 1) + range.min);
            font-size: tickfontsize;
            x: 0;
            y: 0;
            color: #333;
            horizontal-alignment: right;
        }
    }
}

export component PlotArea inherits Rectangle {
    in-out property <[{linecolor: color, fill: color, linewidth: length,  points: [{ x: float, y: float}]
}

]> linedata: [];
    in-out property <{min: float, max: float}> x-range: { min: 0, max: 1 };
    in-out property <{min: float, max: float}> y-range: { min: 0, max: 1 };
    padding: 0px;

    i-background := Rectangle {
        x: 0;
        y: 0;
        width: parent.width;
        height: parent.height;
        border-color: black;
        border-width: 2px;
    }

    for line in linedata: Path {
        width: parent.width;
        height: parent.height;
        viewbox-width: 100;
        viewbox-height: 100 * parent.height / parent.width;
        stroke: line.linecolor;
        stroke-width: line.linewidth;
        fill: line.fill;
        commands: Shared.linetosvg(line.points, x-range, y-range, parent.height / parent.width);
    }
}

export component DragArea inherits Rectangle {
    in-out property <bool> mindrag: false;
    in-out property <bool> maxdrag: false;

    in-out property <int> fcmin: 0.0;
    in-out property <int> fcmax: 65536;
    in-out property <{min: float, max: float}> range: { min: 0, max: 1 };

    vbmin := VertBar {
        x: parent.width * (fcmin - range.min) / (range.max - range.min) - self.width / 2;
        y: 0;
    }

    vbmax := VertBar {
        x: parent.width * (fcmax - range.min) / (range.max - range.min) - self.width / 2;
        y: 0;
    }

    TouchArea {
        x: 0;
        y: 0;
        width: parent.width;
        height: parent.height;

        pointer-event(event) => {
            if (event.kind == PointerEventKind.down) {
                if (Math.abs(self.mouse-x - (vbmin.x + vbmin.width / 2)) < 4px) {
                    mindrag = true;
                } else if (Math.abs(self.mouse-x - (vbmax.x + vbmax.width / 2)) < 4px) {
                    maxdrag = true;
                }
            }
            if (event.kind == PointerEventKind.up) {
                mindrag = false;
                maxdrag = false;
            }
            if (mindrag) {
                vbmin.x = self.mouse-x - vbmin.width / 2;
                if (vbmin.x < -vbmin.width / 2) {
                    vbmin.x = -vbmin.width / 2;
                }
                if (vbmin.x > vbmax.x - 4px) {
                    vbmin.x = vbmax.x - 4px;
                }
                fcmin = ((vbmin.x + vbmin.width / 2) / parent.width) * (range.max - range.min) + range.min;
                Shared.view_changed();
            }
            if (maxdrag) {
                vbmax.x = self.mouse-x - vbmax.width / 2;
                if (vbmax.x > parent.width - vbmax.width / 2) {
                    vbmax.x = parent.width - vbmax.width / 2;
                }
                if (vbmax.x < vbmin.x + 4px) {
                    vbmax.x = vbmin.x + 4px;
                }
                fcmax = (vbmax.x + vbmax.width / 2) / parent.width * (range.max - range.min) + range.min;
                Shared.view_changed();
            }
        }
    }
}

export component PlotBox inherits Rectangle {
    in-out property <length> labelfontsize: 1.2rem;
    in-out property <length> tickfontsize: 1rem;
    in-out property <string> x-label: "xlabel";
    in-out property <string> y-label: "ylabel";

    i-background := Rectangle {
        x: 0;
        y: 0;
        width: parent.width;
        height: parent.height;
        background: white;
    }

    xaxh := XAxis {
        label <=> root.x-label;
        range <=> Shared.histxrange;
        labelfontsize <=> root.labelfontsize;
        tickfontsize <=> root.tickfontsize;
        x: yaxh.width;
        y: parent.height - xaxh.height;
        width: parent.width - yaxh.width - 16px;
    }

    yaxh := YAxis {
        label <=> root.y-label;
        range <=> Shared.histyrange;
        labelfontsize <=> root.labelfontsize;
        tickfontsize <=> root.tickfontsize;
        x: 0;
        y: 15px;
        height: parent.height - xaxh.height - 16px;
    }

    plotarea := PlotArea {
        x: yaxh.x + yaxh.width;
        y: yaxh.y;
        width: xaxh.width;
        height: yaxh.height;
        x-range <=> Shared.histxrange;
        y-range <=> Shared.histyrange;
        linedata <=> Shared.histdata;
    }

    // This has the vertical drag bars
    // for setting the false color scale from the histogram
    if Shared.manualfc: dah := DragArea {
        x: yaxh.x + yaxh.width;
        y: yaxh.y;
        width: xaxh.width;
        height: yaxh.height;
        fcmin <=> Shared.manualfc_min;
        fcmax <=> Shared.manualfc_max;
        range <=> Shared.histxrange;
    }
}
