import {PlotRange, PlotData, MarkerType, PlotType, PlotPoint} from "plotting.slint";

export global Shared {
    in-out property <PlotRange> histxrange: { min: 0, max: 10 };
    in-out property <PlotRange> histyrange: { min: 0, max: 10 };
    in-out property <[PlotData]> histdata: [];
    in-out property <[float]> histxticks: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
    in-out property <[float]> histyticks: [0, 2, 4, 6, 8, 10];
    in-out property <string> framerate: "";
    in-out property <bool> autoscale: false;
    in-out property <bool> manualfc: false;
    in-out property <int> manualfc_min: 0;
    in-out property <int> manualfc_max: 65536;
    in-out property <{min: int, max: int}> colorscale;
    in-out property <string> colormap: "Parula";
    in-out property <float> gamma: 1.0;
    in-out property <{min: int, max: int}> fcrange: { min: 0, max: 65536 };
    // Region of interest for statistics, etc...
    in-out property <{x: int, y: int, width: int, height: int}> roi: { x: 0, y: 0, width: 0, height: 0 };
    pure callback displayimage(length, length) -> image;

    callback view_changed();
    pure callback mouseover_string(int, int, int) -> string;
}
