export global Shared {
    pure callback linetosvg(points: [{x: float, y: float}], xrange: {min: float, max: float}, yrange: {min: float, max: float}, aspect: float) -> string;
    in-out property <[{linecolor: color, linewidth: length, points: [{x: float, y: float}]}]> histdata: [];
    in-out property <{min: float, max: float}> histxrange: { min: 0, max: 1 };
    in-out property <{min: float, max: float}> histyrange: { min: 0, max: 1 };
    in-out property <bool> autoscale: false;
    in-out property <{min: int, max: int}> colorscale;
    in-out property <string> colormap: "Parula";
    in-out property <float> gamma: 1.0;
    in-out property <float> histaspect;
    in-out property <{min: int, max: int}> fcrange: { min: 0, max: 65536 };

    callback view_changed();
}
