import {Palette} from "std-widgets.slint";

export component ToggleSwitch inherits Rectangle {
    callback toggled(bool);
    in-out property <string> text;
    in-out property <bool> checked;
    in-out property <bool> enabled <=> touch-area.enabled;
    preferred-height: 20px;
    horizontal-stretch: 0;
    vertical-stretch: 0;

    HorizontalLayout {
        spacing: 8px;
        indicator := Rectangle {
            width: 40px;
            border-width: 1px;
            border-radius: root.height / 2;
            border-color: self.background.darker(25%);
            background: root.enabled ? (root.checked ? Palette.selection-background : Palette.background) : white;
            animate background { duration: 100ms; }

            bubble := Rectangle {
                width: root.height - 8px;
                height: bubble.width;
                border-radius: bubble.height / 2;
                y: 4px;
                x: 4px + self.a * (indicator.width - bubble.width - 8px);
                property <float> a: root.checked ? 1 : 0;
                //background: root.checked ? Palette.accent-foreground : (root.enabled ? Palette.accent-background : gray);
                background: root.enabled ? (root.checked ? Palette.background : Palette.selection-background.darker(1.2)) : gray;
                animate a, background {
                    duration: 250ms;
                    easing: ease;
                }
            }
        }

        Text {
            min-width: max(100px, self.preferred-width);
            text: root.text;
            vertical-alignment: center;
            color: root.enabled ? black : gray;
        }
    }

    touch-area := TouchArea {
        width: root.width;
        height: root.height;
        clicked => {
            if (root.enabled) {
                root.checked = !root.checked;
                root.toggled(root.checked);
            }
        }
    }
}
